services:
  - type: web
    name: siscoen
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn siscoen.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: siscoen.settings
