"""
Django settings for siscoen project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h_fem8z%9q7g50ph$a(_@o49*ybv0dhrt=@p+gl1wmu(#nvc%j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'escala',
    'import_export',
]

JAZZMIN_SETTINGS = {
    "site_title": "SISCOEN Admin",
    "site_header": "SISCOEN",
    "site_brand": "SISCOEN",
    "site_logo": "/static/images/logo_uerj.png",
    "login_logo": "/static/images/logo_colorida_uerj.png",
    "login_logo_dark": "/static/images/logo_colorida_uerj.png",
    "welcome_sign": "Bem-vindo ao Sistema de Controle de Escalas (SISCOEN)",
    "copyright": "SISCOEN - Beatriz Machado",
    "search_model": ["auth.User", "auth.Group"],
    "user_avatar": False,

    # Links no topo do admin
    "topmenu_links": [
        {"name": "Início", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Colaboradores", "url": "/colaboradores/", "permissions": ["escala.view_colaborador"]},
        {"name": "Escala Macro", "url": "/escala/macro/", "permissions": ["escala.view_escala"]},
        {"name": "Sobre", "url": "/sobre/", "permissions": ["auth.view_user"]},
    ],

    # Links no menu do usuário (canto superior direito)
    "usermenu_links": [
        {"name": "Perfil", "url": "admin:auth_user_change", "permissions": ["auth.view_user"]},
        {"model": "auth.user"}
    ],

    # Menu lateral
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["escala", "auth", "sites"],

    # Ícones para os modelos
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "escala.Colaborador": "fas fa-user-nurse",
        "escala.Setor": "fas fa-building",
        "escala.Categoria": "fas fa-layer-group",
        "escala.Plantao": "fas fa-calendar-alt",
    },

    # Modais ao invés de popups
    "related_modal_active": True,

    # Personalização do CSS e JS
    "custom_css": "/static/jazzmin/css/custom.css",
    "custom_js": "/static/jazzmin/js/custom.js",
    "use_google_fonts_cdn": True,

    # Formato do formulário de alteração
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},

    # Ativa o uso do Google Fonts
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'siscoen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siscoen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'escala/templates/assets',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
