# Generated by Django 5.1 on 2025-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_categoria_alter_colaborador_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantao',
            name='turno',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('AB', 'Abono'), ('FE', 'Férias'), ('F', 'Folga')], default='F', max_length=2),
        ),
    ]
